In [5]:
import pandas as pd
survey = pd.read_csv('data/coffee-survey-results.csv')
survey #display dataframe

,SubmissionID,What is your age range?,How many cups of coffee do you consume per day?,Do you add any dairy or dairy alternative to your coffee?,What kind of dairy? (Whole milk),What kind of dairy? (Skim milk),What kind of dairy? (Half and half),What kind of dairy? (Coffee creamer),What kind of dairy? (Flavored creamer),What kind of dairy? (Oat milk),...,What kind of sugar or sweetener? (Raw Sugar),How do you brew your coffee? (Pour over),How do you brew your coffee? (French press),How do you brew your coffee? (Espresso),How do you brew your coffee? (Coffee brewing machine),How do you brew your coffee? (Pod/capsule machine),How do you brew your coffee? (Instant coffee),How do you brew your coffee? (Bean-to-cup machine),How do you brew your coffee? (Cold brew),How do you brew your coffee? (Coffee extract)
0,VZbv6N,35-44,< 1,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,jBGZBQ,25-34,< 1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7d9809,18-24,1,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,bl62ee,45-54,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,BGbJ9Q,25-34,2,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1165,ZdR7Dy,18-24,2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,LdMr0l,35-44,2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1167,ylqaYX,18-24,< 1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1168,KMBEyk,25-34,3,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1169,g5ggRM,18-24,1,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,NaN,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0

In [6]:
survey.columns

Index(['SubmissionID', 'What is your age range?',
       'How many cups of coffee do you consume per day?',
       'Do you add any dairy or dairy alternative to your coffee?',
       'What kind of dairy? (Whole milk)', 'What kind of dairy? (Skim milk)',
       'What kind of dairy? (Half and half)',
       'What kind of dairy? (Coffee creamer)',
       'What kind of dairy? (Flavored creamer)',
       'What kind of dairy? (Oat milk)', 'What kind of dairy? (Almond milk)',
       'What kind of dairy? (Soy milk)',
       'Do you add any sugar or sweetener to your coffee?',
       'What kind of sugar or sweetener? (Granulated Sugar)',
       'What kind of sugar or sweetener? (Artificial Sweetener)',
       'What kind of sugar or sweetener? (Honey)',
       'What kind of sugar or sweetener? (Maple Syrup)',
       'What kind of sugar or sweetener? (Stevia)',
       'What kind of sugar or sweetener? (Agave Nectar)',
       'What kind of sugar or sweetener? (Brown Sugar)',
       'What kind of sugar or sweetener? (Raw Sugar)',
       'How do you brew your coffee? (Pour over)',
       'How do you brew your coffee? (French press)',
       'How do you brew your coffee? (Espresso)',
       'How do you brew your coffee? (Coffee brewing machine)',
       'How do you brew your coffee? (Pod/capsule machine)',
       'How do you brew your coffee? (Instant coffee)',
       'How do you brew your coffee? (Bean-to-cup machine)',
       'How do you brew your coffee? (Cold brew)',
       'How do you brew your coffee? (Coffee extract)'],
      dtype='str')

In [8]:
needed_column=['What kind of dairy? (Whole milk)', 'What kind of dairy? (Skim milk)',
       'What kind of dairy? (Half and half)',
       'What kind of dairy? (Coffee creamer)',
       'What kind of dairy? (Flavored creamer)',
       'What kind of dairy? (Oat milk)', 'What kind of dairy? (Almond milk)',
       'What kind of dairy? (Soy milk)']
dairy = survey[needed_column]
dairy

,What kind of dairy? (Whole milk),What kind of dairy? (Skim milk),What kind of dairy? (Half and half),What kind of dairy? (Coffee creamer),What kind of dairy? (Flavored creamer),What kind of dairy? (Oat milk),What kind of dairy? (Almond milk),What kind of dairy? (Soy milk)
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
1165,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1166,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1168,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1169,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0

In [14]:
name_map = {'What kind of dairy? (Whole milk)':'Whole milk',
            'What kind of dairy? (Skim milk)':'Skim milk',
            'What kind of dairy? (Half and half)':'Half and half',
            'What kind of dairy? (Coffee creamer)':'Coffee creamer',
            'What kind of dairy? (Flavored creamer)':'Flavoured creamer',
            'What kind of dairy? (Oat milk)':'Oat milk',
            'What kind of dairy? (Almond milk)':'Almond milk',
            'What kind of dairy? (Soy milk)':'Soy milk'}
dairy = dairy.rename(columns=name_map)
dairy

,Whole milk,Skim milk,Half and half,Coffee creamer,Flavoured creamer,Oat milk,Almond milk,Soy milk
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
1165,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1166,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1168,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1169,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0

In [21]:
dairy.isna().sum()

Whole milk           0
Skim milk            0
Half and half        0
Coffee creamer       0
Flavoured creamer    0
Oat milk             0
Almond milk          0
Soy milk             0
dtype: int64

In [17]:
dairy = dairy.dropna()
dairy

,Whole milk,Skim milk,Half and half,Coffee creamer,Flavoured creamer,Oat milk,Almond milk,Soy milk
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
5,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
1164,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1165,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1166,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1168,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1169,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0

In [19]:
dairy.isna().sum()

Whole milk           0
Skim milk            0
Half and half        0
Coffee creamer       0
Flavoured creamer    0
Oat milk             0
Almond milk          0
Soy milk             0
dtype: int64

In [ ]:
dairy_prefreance =